# Generated by Django 4.2.7 on 2023-11-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='exercises',
            new_name='activities',
        ),
    ]
