# Generated by Django 4.2.7 on 2023-11-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_exercisesteps_activitiessteps_and_more'),
        ('activity_tracker', '0002_remove_completedactivity_activity_activitysession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysession',
            name='activity',
        ),
        migrations.AddField(
            model_name='activitysession',
            name='activity',
            field=models.ManyToManyField(to='activities.activity'),
        ),
    ]
