# Generated by Django 4.2.7 on 2023-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_tracker', '0003_remove_activitysession_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysession',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
