# Generated by Django 4.2.7 on 2023-11-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_tracker', '0005_remove_completedactivity_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysession',
            name='date_completed',
            field=models.DateField(blank=True),
        ),
    ]
