# Generated by Django 4.2.7 on 2023-11-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_tracker', '0006_alter_activitysession_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysession',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
