# Generated by Django 4.2.7 on 2023-11-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_exercisesteps_activitiessteps_and_more'),
        ('activity_tracker', '0007_alter_activitysession_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedactivity',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
    ]
